project:
  type: website

website:
  site-url: https://nanoyan.github.io/visor/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/nanoyan/visor/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
      - text: "Schemas"
        href: response.qmd
    right:
      - icon: github
        href: https://github.com/nanoyan/visor/
        aria-label: Source Code


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



