project:
  type: website

website:
  site-url: https://nanoyan.github.io/visor/index.html
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/nanoyan/visor/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
      - text: "Index"
        href: index.qmd
      - text: "Response"
        href: templates/response.html
      - text: "Missing"
        href: templates/missing.html
      - text: "Coding Scheme"
        href: templates/coding-scheme.html
      - text: "State Map"
        href: templates/state-map.html
    right:
      - icon: github
        href: https://github.com/nanoyan/visor/
        aria-label: Source Code


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true